// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nschimek/nice-fixture-feeder/model"
	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// Requester is an autogenerated mock type for the Requester type
type Requester[T interface{}] struct {
	mock.Mock
}

type Requester_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *Requester[T]) EXPECT() *Requester_Expecter[T] {
	return &Requester_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function with given fields: endpoint, params
func (_m *Requester[T]) Get(endpoint string, params url.Values) (*model.Response[T], error) {
	ret := _m.Called(endpoint, params)

	var r0 *model.Response[T]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, url.Values) (*model.Response[T], error)); ok {
		return rf(endpoint, params)
	}
	if rf, ok := ret.Get(0).(func(string, url.Values) *model.Response[T]); ok {
		r0 = rf(endpoint, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Response[T])
		}
	}

	if rf, ok := ret.Get(1).(func(string, url.Values) error); ok {
		r1 = rf(endpoint, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Requester_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Requester_Get_Call[T interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - endpoint string
//   - params url.Values
func (_e *Requester_Expecter[T]) Get(endpoint interface{}, params interface{}) *Requester_Get_Call[T] {
	return &Requester_Get_Call[T]{Call: _e.mock.On("Get", endpoint, params)}
}

func (_c *Requester_Get_Call[T]) Run(run func(endpoint string, params url.Values)) *Requester_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(url.Values))
	})
	return _c
}

func (_c *Requester_Get_Call[T]) Return(_a0 *model.Response[T], _a1 error) *Requester_Get_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Requester_Get_Call[T]) RunAndReturn(run func(string, url.Values) (*model.Response[T], error)) *Requester_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRequester interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequester creates a new instance of Requester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequester[T interface{}](t mockConstructorTestingTNewRequester) *Requester[T] {
	mock := &Requester[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
