// Code generated by mockery v2.28.0. DO NOT EDIT.

package request

import (
	time "time"

	model "github.com/nschimek/nice-fixture-feeder/model"
	mock "github.com/stretchr/testify/mock"
)

// MockFixtureRequest is an autogenerated mock type for the FixtureRequest type
type MockFixtureRequest struct {
	mock.Mock
}

type MockFixtureRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFixtureRequest) EXPECT() *MockFixtureRequest_Expecter {
	return &MockFixtureRequest_Expecter{mock: &_m.Mock}
}

// GetIds provides a mock function with given fields:
func (_m *MockFixtureRequest) GetIds() []int {
	ret := _m.Called()

	var r0 []int
	if rf, ok := ret.Get(0).(func() []int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// MockFixtureRequest_GetIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIds'
type MockFixtureRequest_GetIds_Call struct {
	*mock.Call
}

// GetIds is a helper method to define mock.On call
func (_e *MockFixtureRequest_Expecter) GetIds() *MockFixtureRequest_GetIds_Call {
	return &MockFixtureRequest_GetIds_Call{Call: _e.mock.On("GetIds")}
}

func (_c *MockFixtureRequest_GetIds_Call) Run(run func()) *MockFixtureRequest_GetIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFixtureRequest_GetIds_Call) Return(_a0 []int) *MockFixtureRequest_GetIds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFixtureRequest_GetIds_Call) RunAndReturn(run func() []int) *MockFixtureRequest_GetIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetMap provides a mock function with given fields:
func (_m *MockFixtureRequest) GetMap() map[int]model.Fixture {
	ret := _m.Called()

	var r0 map[int]model.Fixture
	if rf, ok := ret.Get(0).(func() map[int]model.Fixture); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]model.Fixture)
		}
	}

	return r0
}

// MockFixtureRequest_GetMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMap'
type MockFixtureRequest_GetMap_Call struct {
	*mock.Call
}

// GetMap is a helper method to define mock.On call
func (_e *MockFixtureRequest_Expecter) GetMap() *MockFixtureRequest_GetMap_Call {
	return &MockFixtureRequest_GetMap_Call{Call: _e.mock.On("GetMap")}
}

func (_c *MockFixtureRequest_GetMap_Call) Run(run func()) *MockFixtureRequest_GetMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFixtureRequest_GetMap_Call) Return(_a0 map[int]model.Fixture) *MockFixtureRequest_GetMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFixtureRequest_GetMap_Call) RunAndReturn(run func() map[int]model.Fixture) *MockFixtureRequest_GetMap_Call {
	_c.Call.Return(run)
	return _c
}

// Persist provides a mock function with given fields:
func (_m *MockFixtureRequest) Persist() {
	_m.Called()
}

// MockFixtureRequest_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type MockFixtureRequest_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
func (_e *MockFixtureRequest_Expecter) Persist() *MockFixtureRequest_Persist_Call {
	return &MockFixtureRequest_Persist_Call{Call: _e.mock.On("Persist")}
}

func (_c *MockFixtureRequest_Persist_Call) Run(run func()) *MockFixtureRequest_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFixtureRequest_Persist_Call) Return() *MockFixtureRequest_Persist_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFixtureRequest_Persist_Call) RunAndReturn(run func()) *MockFixtureRequest_Persist_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields:
func (_m *MockFixtureRequest) Request() {
	_m.Called()
}

// MockFixtureRequest_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockFixtureRequest_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *MockFixtureRequest_Expecter) Request() *MockFixtureRequest_Request_Call {
	return &MockFixtureRequest_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *MockFixtureRequest_Request_Call) Run(run func()) *MockFixtureRequest_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFixtureRequest_Request_Call) Return() *MockFixtureRequest_Request_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFixtureRequest_Request_Call) RunAndReturn(run func()) *MockFixtureRequest_Request_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDateRange provides a mock function with given fields: startDate, endDate
func (_m *MockFixtureRequest) RequestDateRange(startDate time.Time, endDate time.Time) {
	_m.Called(startDate, endDate)
}

// MockFixtureRequest_RequestDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDateRange'
type MockFixtureRequest_RequestDateRange_Call struct {
	*mock.Call
}

// RequestDateRange is a helper method to define mock.On call
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockFixtureRequest_Expecter) RequestDateRange(startDate interface{}, endDate interface{}) *MockFixtureRequest_RequestDateRange_Call {
	return &MockFixtureRequest_RequestDateRange_Call{Call: _e.mock.On("RequestDateRange", startDate, endDate)}
}

func (_c *MockFixtureRequest_RequestDateRange_Call) Run(run func(startDate time.Time, endDate time.Time)) *MockFixtureRequest_RequestDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockFixtureRequest_RequestDateRange_Call) Return() *MockFixtureRequest_RequestDateRange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFixtureRequest_RequestDateRange_Call) RunAndReturn(run func(time.Time, time.Time)) *MockFixtureRequest_RequestDateRange_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockFixtureRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFixtureRequest creates a new instance of MockFixtureRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFixtureRequest(t mockConstructorTestingTNewMockFixtureRequest) *MockFixtureRequest {
	mock := &MockFixtureRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
