// Code generated by mockery v2.28.0. DO NOT EDIT.

package request

import (
	url "net/url"

	mock "github.com/stretchr/testify/mock"
)

// MockRequester is an autogenerated mock type for the Requester type
type MockRequester[T interface{}] struct {
	mock.Mock
}

// Get provides a mock function with given fields: endpoint, params
func (_m *MockRequester[T]) Get(endpoint string, params url.Values) (*Response[T], error) {
	ret := _m.Called(endpoint, params)

	var r0 *Response[T]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, url.Values) (*Response[T], error)); ok {
		return rf(endpoint, params)
	}
	if rf, ok := ret.Get(0).(func(string, url.Values) *Response[T]); ok {
		r0 = rf(endpoint, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response[T])
		}
	}

	if rf, ok := ret.Get(1).(func(string, url.Values) error); ok {
		r1 = rf(endpoint, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockRequester interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRequester creates a new instance of MockRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRequester[T interface{}](t mockConstructorTestingTNewMockRequester) *MockRequester[T] {
	mock := &MockRequester[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
