// Code generated by mockery v2.28.0. DO NOT EDIT.

package request

import mock "github.com/stretchr/testify/mock"

// MockTeamRequest is an autogenerated mock type for the TeamRequest type
type MockTeamRequest struct {
	mock.Mock
}

type MockTeamRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRequest) EXPECT() *MockTeamRequest_Expecter {
	return &MockTeamRequest_Expecter{mock: &_m.Mock}
}

// Persist provides a mock function with given fields:
func (_m *MockTeamRequest) Persist() {
	_m.Called()
}

// MockTeamRequest_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type MockTeamRequest_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
func (_e *MockTeamRequest_Expecter) Persist() *MockTeamRequest_Persist_Call {
	return &MockTeamRequest_Persist_Call{Call: _e.mock.On("Persist")}
}

func (_c *MockTeamRequest_Persist_Call) Run(run func()) *MockTeamRequest_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamRequest_Persist_Call) Return() *MockTeamRequest_Persist_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamRequest_Persist_Call) RunAndReturn(run func()) *MockTeamRequest_Persist_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields:
func (_m *MockTeamRequest) Request() {
	_m.Called()
}

// MockTeamRequest_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockTeamRequest_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *MockTeamRequest_Expecter) Request() *MockTeamRequest_Request_Call {
	return &MockTeamRequest_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *MockTeamRequest_Request_Call) Run(run func()) *MockTeamRequest_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamRequest_Request_Call) Return() *MockTeamRequest_Request_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamRequest_Request_Call) RunAndReturn(run func()) *MockTeamRequest_Request_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockTeamRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTeamRequest creates a new instance of MockTeamRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTeamRequest(t mockConstructorTestingTNewMockTeamRequest) *MockTeamRequest {
	mock := &MockTeamRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
