// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FixtureStatus is an autogenerated mock type for the FixtureStatus type
type FixtureStatus struct {
	mock.Mock
}

type FixtureStatus_Expecter struct {
	mock *mock.Mock
}

func (_m *FixtureStatus) EXPECT() *FixtureStatus_Expecter {
	return &FixtureStatus_Expecter{mock: &_m.Mock}
}

// GetType provides a mock function with given fields: id
func (_m *FixtureStatus) GetType(id string) string {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FixtureStatus_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type FixtureStatus_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
//   - id string
func (_e *FixtureStatus_Expecter) GetType(id interface{}) *FixtureStatus_GetType_Call {
	return &FixtureStatus_GetType_Call{Call: _e.mock.On("GetType", id)}
}

func (_c *FixtureStatus_GetType_Call) Run(run func(id string)) *FixtureStatus_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FixtureStatus_GetType_Call) Return(_a0 string) *FixtureStatus_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FixtureStatus_GetType_Call) RunAndReturn(run func(string) string) *FixtureStatus_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// IsFinished provides a mock function with given fields: id
func (_m *FixtureStatus) IsFinished(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FixtureStatus_IsFinished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFinished'
type FixtureStatus_IsFinished_Call struct {
	*mock.Call
}

// IsFinished is a helper method to define mock.On call
//   - id string
func (_e *FixtureStatus_Expecter) IsFinished(id interface{}) *FixtureStatus_IsFinished_Call {
	return &FixtureStatus_IsFinished_Call{Call: _e.mock.On("IsFinished", id)}
}

func (_c *FixtureStatus_IsFinished_Call) Run(run func(id string)) *FixtureStatus_IsFinished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FixtureStatus_IsFinished_Call) Return(_a0 bool) *FixtureStatus_IsFinished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FixtureStatus_IsFinished_Call) RunAndReturn(run func(string) bool) *FixtureStatus_IsFinished_Call {
	_c.Call.Return(run)
	return _c
}

// IsScheduled provides a mock function with given fields: id
func (_m *FixtureStatus) IsScheduled(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FixtureStatus_IsScheduled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScheduled'
type FixtureStatus_IsScheduled_Call struct {
	*mock.Call
}

// IsScheduled is a helper method to define mock.On call
//   - id string
func (_e *FixtureStatus_Expecter) IsScheduled(id interface{}) *FixtureStatus_IsScheduled_Call {
	return &FixtureStatus_IsScheduled_Call{Call: _e.mock.On("IsScheduled", id)}
}

func (_c *FixtureStatus_IsScheduled_Call) Run(run func(id string)) *FixtureStatus_IsScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FixtureStatus_IsScheduled_Call) Return(_a0 bool) *FixtureStatus_IsScheduled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FixtureStatus_IsScheduled_Call) RunAndReturn(run func(string) bool) *FixtureStatus_IsScheduled_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFixtureStatus interface {
	mock.TestingT
	Cleanup(func())
}

// NewFixtureStatus creates a new instance of FixtureStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFixtureStatus(t mockConstructorTestingTNewFixtureStatus) *FixtureStatus {
	mock := &FixtureStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
