// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nschimek/nice-fixture-feeder/model"
	mock "github.com/stretchr/testify/mock"
)

// TeamLeagueSeason is an autogenerated mock type for the TeamLeagueSeason type
type TeamLeagueSeason struct {
	mock.Mock
}

type TeamLeagueSeason_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamLeagueSeason) EXPECT() *TeamLeagueSeason_Expecter {
	return &TeamLeagueSeason_Expecter{mock: &_m.Mock}
}

// AddToMap provides a mock function with given fields: tls
func (_m *TeamLeagueSeason) AddToMap(tls *model.TeamLeagueSeason) {
	_m.Called(tls)
}

// TeamLeagueSeason_AddToMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToMap'
type TeamLeagueSeason_AddToMap_Call struct {
	*mock.Call
}

// AddToMap is a helper method to define mock.On call
//   - tls *model.TeamLeagueSeason
func (_e *TeamLeagueSeason_Expecter) AddToMap(tls interface{}) *TeamLeagueSeason_AddToMap_Call {
	return &TeamLeagueSeason_AddToMap_Call{Call: _e.mock.On("AddToMap", tls)}
}

func (_c *TeamLeagueSeason_AddToMap_Call) Run(run func(tls *model.TeamLeagueSeason)) *TeamLeagueSeason_AddToMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TeamLeagueSeason))
	})
	return _c
}

func (_c *TeamLeagueSeason_AddToMap_Call) Return() *TeamLeagueSeason_AddToMap_Call {
	_c.Call.Return()
	return _c
}

func (_c *TeamLeagueSeason_AddToMap_Call) RunAndReturn(run func(*model.TeamLeagueSeason)) *TeamLeagueSeason_AddToMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: tsid
func (_m *TeamLeagueSeason) GetById(tsid model.TeamLeagueSeasonId) (*model.TeamLeagueSeason, error) {
	ret := _m.Called(tsid)

	var r0 *model.TeamLeagueSeason
	var r1 error
	if rf, ok := ret.Get(0).(func(model.TeamLeagueSeasonId) (*model.TeamLeagueSeason, error)); ok {
		return rf(tsid)
	}
	if rf, ok := ret.Get(0).(func(model.TeamLeagueSeasonId) *model.TeamLeagueSeason); ok {
		r0 = rf(tsid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TeamLeagueSeason)
		}
	}

	if rf, ok := ret.Get(1).(func(model.TeamLeagueSeasonId) error); ok {
		r1 = rf(tsid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamLeagueSeason_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type TeamLeagueSeason_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - tsid model.TeamLeagueSeasonId
func (_e *TeamLeagueSeason_Expecter) GetById(tsid interface{}) *TeamLeagueSeason_GetById_Call {
	return &TeamLeagueSeason_GetById_Call{Call: _e.mock.On("GetById", tsid)}
}

func (_c *TeamLeagueSeason_GetById_Call) Run(run func(tsid model.TeamLeagueSeasonId)) *TeamLeagueSeason_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TeamLeagueSeasonId))
	})
	return _c
}

func (_c *TeamLeagueSeason_GetById_Call) Return(_a0 *model.TeamLeagueSeason, _a1 error) *TeamLeagueSeason_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamLeagueSeason_GetById_Call) RunAndReturn(run func(model.TeamLeagueSeasonId) (*model.TeamLeagueSeason, error)) *TeamLeagueSeason_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Persist provides a mock function with given fields:
func (_m *TeamLeagueSeason) Persist() {
	_m.Called()
}

// TeamLeagueSeason_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type TeamLeagueSeason_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
func (_e *TeamLeagueSeason_Expecter) Persist() *TeamLeagueSeason_Persist_Call {
	return &TeamLeagueSeason_Persist_Call{Call: _e.mock.On("Persist")}
}

func (_c *TeamLeagueSeason_Persist_Call) Run(run func()) *TeamLeagueSeason_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeamLeagueSeason_Persist_Call) Return() *TeamLeagueSeason_Persist_Call {
	_c.Call.Return()
	return _c
}

func (_c *TeamLeagueSeason_Persist_Call) RunAndReturn(run func()) *TeamLeagueSeason_Persist_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewTeamLeagueSeason interface {
	mock.TestingT
	Cleanup(func())
}

// NewTeamLeagueSeason creates a new instance of TeamLeagueSeason. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTeamLeagueSeason(t mockConstructorTestingTNewTeamLeagueSeason) *TeamLeagueSeason {
	mock := &TeamLeagueSeason{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
