// Code generated by mockery v2.28.0. DO NOT EDIT.

package service

import (
	model "github.com/nschimek/nice-fixture-feeder/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTeamStatsService is an autogenerated mock type for the TeamStatsService type
type MockTeamStatsService struct {
	mock.Mock
}

type MockTeamStatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamStatsService) EXPECT() *MockTeamStatsService_Expecter {
	return &MockTeamStatsService_Expecter{mock: &_m.Mock}
}

// MaintainStats provides a mock function with given fields: fixtureIds, fixtureMap
func (_m *MockTeamStatsService) MaintainStats(fixtureIds []int, fixtureMap map[int]model.Fixture) {
	_m.Called(fixtureIds, fixtureMap)
}

// MockTeamStatsService_MaintainStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaintainStats'
type MockTeamStatsService_MaintainStats_Call struct {
	*mock.Call
}

// MaintainStats is a helper method to define mock.On call
//   - fixtureIds []int
//   - fixtureMap map[int]model.Fixture
func (_e *MockTeamStatsService_Expecter) MaintainStats(fixtureIds interface{}, fixtureMap interface{}) *MockTeamStatsService_MaintainStats_Call {
	return &MockTeamStatsService_MaintainStats_Call{Call: _e.mock.On("MaintainStats", fixtureIds, fixtureMap)}
}

func (_c *MockTeamStatsService_MaintainStats_Call) Run(run func(fixtureIds []int, fixtureMap map[int]model.Fixture)) *MockTeamStatsService_MaintainStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int), args[1].(map[int]model.Fixture))
	})
	return _c
}

func (_c *MockTeamStatsService_MaintainStats_Call) Return() *MockTeamStatsService_MaintainStats_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamStatsService_MaintainStats_Call) RunAndReturn(run func([]int, map[int]model.Fixture)) *MockTeamStatsService_MaintainStats_Call {
	_c.Call.Return(run)
	return _c
}

// Persist provides a mock function with given fields:
func (_m *MockTeamStatsService) Persist() {
	_m.Called()
}

// MockTeamStatsService_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type MockTeamStatsService_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
func (_e *MockTeamStatsService_Expecter) Persist() *MockTeamStatsService_Persist_Call {
	return &MockTeamStatsService_Persist_Call{Call: _e.mock.On("Persist")}
}

func (_c *MockTeamStatsService_Persist_Call) Run(run func()) *MockTeamStatsService_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTeamStatsService_Persist_Call) Return() *MockTeamStatsService_Persist_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTeamStatsService_Persist_Call) RunAndReturn(run func()) *MockTeamStatsService_Persist_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockTeamStatsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTeamStatsService creates a new instance of MockTeamStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTeamStatsService(t mockConstructorTestingTNewMockTeamStatsService) *MockTeamStatsService {
	mock := &MockTeamStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
