// Code generated by mockery v2.28.0. DO NOT EDIT.

package core

import mock "github.com/stretchr/testify/mock"

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: value
func (_m *MockDatabase) Upsert(value interface{}) DatabaseResult {
	ret := _m.Called(value)

	var r0 DatabaseResult
	if rf, ok := ret.Get(0).(func(interface{}) DatabaseResult); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(DatabaseResult)
	}

	return r0
}

// UpsertWithOmit provides a mock function with given fields: value, omitColumns
func (_m *MockDatabase) UpsertWithOmit(value interface{}, omitColumns ...string) DatabaseResult {
	_va := make([]interface{}, len(omitColumns))
	for _i := range omitColumns {
		_va[_i] = omitColumns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, value)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 DatabaseResult
	if rf, ok := ret.Get(0).(func(interface{}, ...string) DatabaseResult); ok {
		r0 = rf(value, omitColumns...)
	} else {
		r0 = ret.Get(0).(DatabaseResult)
	}

	return r0
}

type mockConstructorTestingTNewMockDatabase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDatabase(t mockConstructorTestingTNewMockDatabase) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
