// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nschimek/nice-fixture-feeder/model"
	mock "github.com/stretchr/testify/mock"
)

// FixtureStatus is an autogenerated mock type for the FixtureStatus type
type FixtureStatus struct {
	mock.Mock
}

type FixtureStatus_Expecter struct {
	mock *mock.Mock
}

func (_m *FixtureStatus) EXPECT() *FixtureStatus_Expecter {
	return &FixtureStatus_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields:
func (_m *FixtureStatus) GetAll() ([]model.FixtureStatus, error) {
	ret := _m.Called()

	var r0 []model.FixtureStatus
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.FixtureStatus, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.FixtureStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FixtureStatus)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FixtureStatus_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type FixtureStatus_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *FixtureStatus_Expecter) GetAll() *FixtureStatus_GetAll_Call {
	return &FixtureStatus_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *FixtureStatus_GetAll_Call) Run(run func()) *FixtureStatus_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FixtureStatus_GetAll_Call) Return(_a0 []model.FixtureStatus, _a1 error) *FixtureStatus_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FixtureStatus_GetAll_Call) RunAndReturn(run func() ([]model.FixtureStatus, error)) *FixtureStatus_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFixtureStatus interface {
	mock.TestingT
	Cleanup(func())
}

// NewFixtureStatus creates a new instance of FixtureStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFixtureStatus(t mockConstructorTestingTNewFixtureStatus) *FixtureStatus {
	mock := &FixtureStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
