// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpsertRepository is an autogenerated mock type for the UpsertRepository type
type UpsertRepository[T interface{}] struct {
	mock.Mock
}

type UpsertRepository_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *UpsertRepository[T]) EXPECT() *UpsertRepository_Expecter[T] {
	return &UpsertRepository_Expecter[T]{mock: &_m.Mock}
}

// Upsert provides a mock function with given fields: entities
func (_m *UpsertRepository[T]) Upsert(entities []T) ([]T, error) {
	ret := _m.Called(entities)

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func([]T) ([]T, error)); ok {
		return rf(entities)
	}
	if rf, ok := ret.Get(0).(func([]T) []T); ok {
		r0 = rf(entities)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func([]T) error); ok {
		r1 = rf(entities)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type UpsertRepository_Upsert_Call[T interface{}] struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - entities []T
func (_e *UpsertRepository_Expecter[T]) Upsert(entities interface{}) *UpsertRepository_Upsert_Call[T] {
	return &UpsertRepository_Upsert_Call[T]{Call: _e.mock.On("Upsert", entities)}
}

func (_c *UpsertRepository_Upsert_Call[T]) Run(run func(entities []T)) *UpsertRepository_Upsert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]T))
	})
	return _c
}

func (_c *UpsertRepository_Upsert_Call[T]) Return(_a0 []T, _a1 error) *UpsertRepository_Upsert_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpsertRepository_Upsert_Call[T]) RunAndReturn(run func([]T) ([]T, error)) *UpsertRepository_Upsert_Call[T] {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUpsertRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpsertRepository creates a new instance of UpsertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpsertRepository[T interface{}](t mockConstructorTestingTNewUpsertRepository) *UpsertRepository[T] {
	mock := &UpsertRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
