// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nschimek/nice-fixture-feeder/model"
	scores "github.com/nschimek/nice-fixture-feeder/service/scores"
	mock "github.com/stretchr/testify/mock"
)

// PointsStrength is an autogenerated mock type for the PointsStrength type
type PointsStrength struct {
	mock.Mock
}

type PointsStrength_Expecter struct {
	mock *mock.Mock
}

func (_m *PointsStrength) EXPECT() *PointsStrength_Expecter {
	return &PointsStrength_Expecter{mock: &_m.Mock}
}

// CanScore provides a mock function with given fields: fixture
func (_m *PointsStrength) CanScore(fixture *model.Fixture) bool {
	ret := _m.Called(fixture)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*model.Fixture) bool); ok {
		r0 = rf(fixture)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PointsStrength_CanScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanScore'
type PointsStrength_CanScore_Call struct {
	*mock.Call
}

// CanScore is a helper method to define mock.On call
//   - fixture *model.Fixture
func (_e *PointsStrength_Expecter) CanScore(fixture interface{}) *PointsStrength_CanScore_Call {
	return &PointsStrength_CanScore_Call{Call: _e.mock.On("CanScore", fixture)}
}

func (_c *PointsStrength_CanScore_Call) Run(run func(fixture *model.Fixture)) *PointsStrength_CanScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Fixture))
	})
	return _c
}

func (_c *PointsStrength_CanScore_Call) Return(_a0 bool) *PointsStrength_CanScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PointsStrength_CanScore_Call) RunAndReturn(run func(*model.Fixture) bool) *PointsStrength_CanScore_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function with given fields:
func (_m *PointsStrength) GetId() scores.ScoreId {
	ret := _m.Called()

	var r0 scores.ScoreId
	if rf, ok := ret.Get(0).(func() scores.ScoreId); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(scores.ScoreId)
	}

	return r0
}

// PointsStrength_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type PointsStrength_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *PointsStrength_Expecter) GetId() *PointsStrength_GetId_Call {
	return &PointsStrength_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *PointsStrength_GetId_Call) Run(run func()) *PointsStrength_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PointsStrength_GetId_Call) Return(_a0 scores.ScoreId) *PointsStrength_GetId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PointsStrength_GetId_Call) RunAndReturn(run func() scores.ScoreId) *PointsStrength_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// Score provides a mock function with given fields: fixture
func (_m *PointsStrength) Score(fixture *model.Fixture) (*model.FixtureScore, error) {
	ret := _m.Called(fixture)

	var r0 *model.FixtureScore
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Fixture) (*model.FixtureScore, error)); ok {
		return rf(fixture)
	}
	if rf, ok := ret.Get(0).(func(*model.Fixture) *model.FixtureScore); ok {
		r0 = rf(fixture)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FixtureScore)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Fixture) error); ok {
		r1 = rf(fixture)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PointsStrength_Score_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Score'
type PointsStrength_Score_Call struct {
	*mock.Call
}

// Score is a helper method to define mock.On call
//   - fixture *model.Fixture
func (_e *PointsStrength_Expecter) Score(fixture interface{}) *PointsStrength_Score_Call {
	return &PointsStrength_Score_Call{Call: _e.mock.On("Score", fixture)}
}

func (_c *PointsStrength_Score_Call) Run(run func(fixture *model.Fixture)) *PointsStrength_Score_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Fixture))
	})
	return _c
}

func (_c *PointsStrength_Score_Call) Return(_a0 *model.FixtureScore, _a1 error) *PointsStrength_Score_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PointsStrength_Score_Call) RunAndReturn(run func(*model.Fixture) (*model.FixtureScore, error)) *PointsStrength_Score_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatsFunc provides a mock function with given fields: _a0
func (_m *PointsStrength) SetStatsFunc(_a0 func(*model.Fixture) (*model.TeamStats, *model.TeamStats, error)) {
	_m.Called(_a0)
}

// PointsStrength_SetStatsFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatsFunc'
type PointsStrength_SetStatsFunc_Call struct {
	*mock.Call
}

// SetStatsFunc is a helper method to define mock.On call
//   - _a0 func(*model.Fixture)(*model.TeamStats , *model.TeamStats , error)
func (_e *PointsStrength_Expecter) SetStatsFunc(_a0 interface{}) *PointsStrength_SetStatsFunc_Call {
	return &PointsStrength_SetStatsFunc_Call{Call: _e.mock.On("SetStatsFunc", _a0)}
}

func (_c *PointsStrength_SetStatsFunc_Call) Run(run func(_a0 func(*model.Fixture) (*model.TeamStats, *model.TeamStats, error))) *PointsStrength_SetStatsFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*model.Fixture) (*model.TeamStats, *model.TeamStats, error)))
	})
	return _c
}

func (_c *PointsStrength_SetStatsFunc_Call) Return() *PointsStrength_SetStatsFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *PointsStrength_SetStatsFunc_Call) RunAndReturn(run func(func(*model.Fixture) (*model.TeamStats, *model.TeamStats, error))) *PointsStrength_SetStatsFunc_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewPointsStrength interface {
	mock.TestingT
	Cleanup(func())
}

// NewPointsStrength creates a new instance of PointsStrength. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPointsStrength(t mockConstructorTestingTNewPointsStrength) *PointsStrength {
	mock := &PointsStrength{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
