// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cache is an autogenerated mock type for the Cache type
type Cache[T interface{}] struct {
	mock.Mock
}

type Cache_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *Cache[T]) EXPECT() *Cache_Expecter[T] {
	return &Cache_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *Cache[T]) Get(key interface{}) (*T, error) {
	ret := _m.Called(key)

	var r0 *T
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*T, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *T); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Cache_Get_Call[T interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key interface{}
func (_e *Cache_Expecter[T]) Get(key interface{}) *Cache_Get_Call[T] {
	return &Cache_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *Cache_Get_Call[T]) Run(run func(key interface{})) *Cache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Cache_Get_Call[T]) Return(_a0 *T, _a1 error) *Cache_Get_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cache_Get_Call[T]) RunAndReturn(run func(interface{}) (*T, error)) *Cache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *Cache[T]) Set(key interface{}, value *T) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, *T) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Cache_Set_Call[T interface{}] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key interface{}
//   - value *T
func (_e *Cache_Expecter[T]) Set(key interface{}, value interface{}) *Cache_Set_Call[T] {
	return &Cache_Set_Call[T]{Call: _e.mock.On("Set", key, value)}
}

func (_c *Cache_Set_Call[T]) Run(run func(key interface{}, value *T)) *Cache_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(*T))
	})
	return _c
}

func (_c *Cache_Set_Call[T]) Return(_a0 error) *Cache_Set_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_Set_Call[T]) RunAndReturn(run func(interface{}, *T) error) *Cache_Set_Call[T] {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCache[T interface{}](t mockConstructorTestingTNewCache) *Cache[T] {
	mock := &Cache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
